-- Air quality data seed
-- Generated by dataset-analysis/scripts/build_air_quality_assets.py

DROP TABLE IF EXISTS public.environment_air_quality_stations;
CREATE TABLE public.environment_air_quality_stations (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    site_id integer,
    site_name text,
    status text,
    aqi double precision,
    pollutant text,
    so2_ppb double precision,
    co_ppm double precision,
    o3_ppb double precision,
    o3_8hr_ppb double precision,
    pm10_ug_m3 double precision,
    pm2_5_ug_m3 double precision,
    no2_ppb double precision,
    nox_ppb double precision,
    no_ppb double precision,
    wind_speed_m_sec double precision,
    wind_direction_degree double precision,
    co_8hr_ppm double precision,
    pm2_5_avg_ug_m3 double precision,
    pm10_avg_ug_m3 double precision,
    so2_avg_ppb double precision,
    longitude double precision,
    latitude double precision,
    publish_time text,
    import_date text,
    source_dataset text,
    updated_at text
);

DROP TABLE IF EXISTS public.environment_pressure_index;
CREATE TABLE public.environment_pressure_index (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    period text,
    pressure_type text,
    metric_name text,
    station_count integer,
    avg_aqi double precision,
    max_aqi double precision,
    avg_pm2_5 double precision,
    avg_pm10 double precision,
    avg_o3_8hr double precision,
    worst_status text,
    dominant_pollutant text,
    score double precision,
    unit text,
    source_dataset text,
    updated_at text
);

COPY public.environment_air_quality_stations (city, district, site_id, site_name, status, aqi, pollutant, so2_ppb, co_ppm, o3_ppb, o3_8hr_ppb, pm10_ug_m3, pm2_5_ug_m3, no2_ppb, nox_ppb, no_ppb, wind_speed_m_sec, wind_direction_degree, co_8hr_ppm, pm2_5_avg_ug_m3, pm10_avg_ug_m3, so2_avg_ppb, longitude, latitude, publish_time, import_date, source_dataset, updated_at) FROM stdin;
新北市	三重區	67	三重	普通	65	細懸浮微粒	1.3	1.05	28	40	42	24	36	51.1	14.7	\N	\N	0.6	17.7	37	0	121.4938	25.0726	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	三重區	8	菜寮	普通	67	臭氧八小時	1.1	0.53	49	60	43	21	19	21	1.1	1.4	111	0.3	16.5	35	0	121.481	25.069	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	土城區	5	土城	普通	67	臭氧八小時	1	0.34	52	60	46	17	11	13	1.1	0.7	145	0.3	14.7	37	0	121.4519	24.9825	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	新店區	4	新店	普通	77	臭氧八小時	1.1	0.4	53	63	41	22	14	14.4	0.4	1.8	145	0.3	16.5	31	0	121.5378	24.9772	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	新莊區	7	新莊	普通	69	懸浮微粒	1.2	0.48	48	57	63	23	23	24.2	1	0.6	48	0.3	16.2	47	0	121.4325	25.038	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	板橋區	6	板橋	普通	64	臭氧八小時	1.8	0.59	51	59	46	21	23	24.8	1.3	1.3	151	0.4	16.2	37	1	121.4587	25.013	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	林口區	9	林口	普通	64	臭氧八小時	1.8	0.39	47	59	30	18	15	17	1.4	0.6	94	0.2	14.8	29	1	121.3655	25.078	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	樹林區	311	新北（樹林）	普通	71	臭氧八小時	1.3	0.33	55	61	32	22	8	9.1	1	0.6	95	0.3	17.9	28	1	121.3835	24.949	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	永和區	70	永和	普通	65	細懸浮微粒	1.7	0.72	45	48	42	24	23	25.7	2.1	0.9	118	0.6	17.5	41	1	121.5163	25.017	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	汐止區	2	汐止	良好	50	\N	2.7	0.62	46	54	31	13	15	16.1	1	0.9	27	0.3	12.3	25	1	121.6408	25.0662	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	淡水區	10	淡水	普通	74	臭氧八小時	1.3	0.28	58	62	37	20	13	14.1	0.8	\N	\N	0.2	17.3	32	0	121.4492	25.1645	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	石門區	84	富貴角	對敏感族群不健康	101	臭氧八小時	0.5	0.19	72	71	32	15	1	1.3	0	1.6	93	0.1	12.2	32	1	121.5366	25.2968	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	中山區	12	中山	普通	67	細懸浮微粒	1.2	0.54	41	56	42	19	27	29.6	2.2	1.8	143	0.4	18.5	36	0	121.5265	25.0624	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	北投區	11	士林	普通	56	細懸浮微粒	1.5	0.36	45	56	36	16	16	16.8	0.6	0.3	67	0.3	14.5	33	0	121.5167	25.1033	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	北投區	64	陽明	良好	46	\N	1	0.27	55	50	28	10	5	6.1	0.5	\N	\N	0.2	10.2	25	0	121.5296	25.1827	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	大同區	16	大同	普通	66	細懸浮微粒	0.9	1.05	26	46	43	25	43	57.4	14.3	\N	\N	0.6	17.9	34	0	121.5134	25.0633	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	大安區	14	古亭	普通	67	臭氧八小時	1.7	0.43	50	60	44	21	17	18.3	0.8	0.6	98	0.3	15.1	34	1	121.5296	25.0206	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	松山區	15	松山	普通	64	臭氧八小時	1.6	0.43	45	59	46	20	20	22.3	1.5	1	44	0.3	16.2	39	1	121.5786	25.05	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	萬華區	13	萬華	普通	64	細懸浮微粒	1.4	0.57	38	55	41	24	29	30	1	1.2	138	0.4	17.3	34	0	121.508	25.0465	2026/05/02 18:00:00	\N	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
\.

COPY public.environment_pressure_index (city, district, period, pressure_type, metric_name, station_count, avg_aqi, max_aqi, avg_pm2_5, avg_pm10, avg_o3_8hr, worst_status, dominant_pollutant, score, unit, source_dataset, updated_at) FROM stdin;
新北市	三重區	2026/05/02 18:00:00	空氣	AQI	2	66	67	17.1	36	50	普通	細懸浮微粒	67	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	土城區	2026/05/02 18:00:00	空氣	AQI	1	67	67	14.7	37	60	普通	臭氧八小時	67	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	新店區	2026/05/02 18:00:00	空氣	AQI	1	77	77	16.5	31	63	普通	臭氧八小時	77	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	新莊區	2026/05/02 18:00:00	空氣	AQI	1	69	69	16.2	47	57	普通	懸浮微粒	69	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	板橋區	2026/05/02 18:00:00	空氣	AQI	1	64	64	16.2	37	59	普通	臭氧八小時	64	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	林口區	2026/05/02 18:00:00	空氣	AQI	1	64	64	14.8	29	59	普通	臭氧八小時	64	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	樹林區	2026/05/02 18:00:00	空氣	AQI	1	71	71	17.9	28	61	普通	臭氧八小時	71	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	永和區	2026/05/02 18:00:00	空氣	AQI	1	65	65	17.5	41	48	普通	細懸浮微粒	65	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	汐止區	2026/05/02 18:00:00	空氣	AQI	1	50	50	12.3	25	54	良好	\N	50	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	淡水區	2026/05/02 18:00:00	空氣	AQI	1	74	74	17.3	32	62	普通	臭氧八小時	74	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
新北市	石門區	2026/05/02 18:00:00	空氣	AQI	1	101	101	12.2	32	71	對敏感族群不健康	臭氧八小時	100	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	中山區	2026/05/02 18:00:00	空氣	AQI	1	67	67	18.5	36	56	普通	細懸浮微粒	67	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	北投區	2026/05/02 18:00:00	空氣	AQI	2	51	56	12.35	29	53	普通	細懸浮微粒	56	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	大同區	2026/05/02 18:00:00	空氣	AQI	1	66	66	17.9	34	46	普通	細懸浮微粒	66	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	大安區	2026/05/02 18:00:00	空氣	AQI	1	67	67	15.1	34	60	普通	臭氧八小時	67	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	松山區	2026/05/02 18:00:00	空氣	AQI	1	64	64	16.2	39	59	普通	臭氧八小時	64	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
臺北市	萬華區	2026/05/02 18:00:00	空氣	AQI	1	64	64	17.3	34	55	普通	細懸浮微粒	64	score_0_100	MOENV AQX_P_432	2026-05-02T18:14:37+08:00
\.

CREATE INDEX IF NOT EXISTS environment_air_quality_stations_city_district_idx
ON public.environment_air_quality_stations (city, district);

CREATE INDEX IF NOT EXISTS environment_pressure_index_city_district_type_idx
ON public.environment_pressure_index (city, district, pressure_type);

SELECT pg_catalog.setval(
    'public.environment_air_quality_stations_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_air_quality_stations),
    true
);

SELECT pg_catalog.setval(
    'public.environment_pressure_index_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_pressure_index),
    true
);
