-- Air quality data seed
-- Generated by dataset-analysis/scripts/build_air_quality_assets.py

DROP TABLE IF EXISTS public.environment_air_quality_stations;
CREATE TABLE public.environment_air_quality_stations (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    site_id integer,
    site_name text,
    status text,
    aqi double precision,
    pollutant text,
    so2_ppb double precision,
    co_ppm double precision,
    o3_ppb double precision,
    o3_8hr_ppb double precision,
    pm10_ug_m3 double precision,
    pm2_5_ug_m3 double precision,
    no2_ppb double precision,
    nox_ppb double precision,
    no_ppb double precision,
    wind_speed_m_sec double precision,
    wind_direction_degree double precision,
    co_8hr_ppm double precision,
    pm2_5_avg_ug_m3 double precision,
    pm10_avg_ug_m3 double precision,
    so2_avg_ppb double precision,
    longitude double precision,
    latitude double precision,
    publish_time text,
    import_date text,
    source_dataset text,
    updated_at text
);

DROP TABLE IF EXISTS public.environment_pressure_index;
CREATE TABLE public.environment_pressure_index (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    period text,
    pressure_type text,
    metric_name text,
    station_count integer,
    avg_aqi double precision,
    max_aqi double precision,
    avg_pm2_5 double precision,
    avg_pm10 double precision,
    avg_o3_8hr double precision,
    worst_status text,
    dominant_pollutant text,
    score double precision,
    unit text,
    source_dataset text,
    updated_at text
);

COPY public.environment_air_quality_stations (city, district, site_id, site_name, status, aqi, pollutant, so2_ppb, co_ppm, o3_ppb, o3_8hr_ppb, pm10_ug_m3, pm2_5_ug_m3, no2_ppb, nox_ppb, no_ppb, wind_speed_m_sec, wind_direction_degree, co_8hr_ppm, pm2_5_avg_ug_m3, pm10_avg_ug_m3, so2_avg_ppb, longitude, latitude, publish_time, import_date, source_dataset, updated_at) FROM stdin;
新北市	三重區	67	三重	普通	68	細懸浮微粒	1.5	1.05	22	38	45	23	43	62.1	18.3	\N	\N	0.7	18.6	38	0	121.4938	25.0726	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	三重區	8	菜寮	普通	65	細懸浮微粒	0.9	0.68	43	59	40	21	25	26.8	1.1	0.9	138	0.4	17.6	36	0	121.481	25.069	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	土城區	5	土城	普通	64	臭氧八小時	1	0.43	45	59	40	20	12	12.9	0.8	0.7	1	0.3	15.7	38	0	121.4519	24.9825	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	新店區	4	新店	普通	74	臭氧八小時	0.8	0.36	43	62	26	15	11	11.6	0.4	1	132	0.3	16.9	30	0	121.5378	24.9772	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	新莊區	7	新莊	普通	70	懸浮微粒	1.3	0.56	45	55	48	23	22	22.9	0.4	0.3	14	0.3	18	48	0	121.4325	25.038	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	板橋區	6	板橋	普通	65	細懸浮微粒	1	0.52	46	58	41	22	16	17.4	0.9	0.2	138	0.4	17.7	39	1	121.4587	25.013	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	林口區	9	林口	普通	64	細懸浮微粒	1.6	0.63	35	57	42	25	29	30.6	1.4	0.4	252	0.3	17.4	32	1	121.3655	25.078	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	樹林區	311	新北（樹林）	普通	68	細懸浮微粒	1.2	0.39	42	59	33	20	11	12.8	1.2	0	338	0.3	18.6	29	1	121.3835	24.949	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	永和區	70	永和	普通	66	細懸浮微粒	1.4	0.6	40	48	34	19	16	17.4	0.9	0.7	92	0.6	17.9	39	1	121.5163	25.017	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	汐止區	2	汐止	普通	52	細懸浮微粒	3.8	0.56	34	53	32	17	22	23.9	1	0.8	17	0.3	12.9	27	1	121.6408	25.0662	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	淡水區	10	淡水	普通	74	臭氧八小時	1.1	0.38	48	62	42	20	14	14.9	0.4	\N	\N	0.2	17.5	34	0	121.4492	25.1645	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	石門區	84	富貴角	對敏感族群不健康	108	臭氧八小時	0.4	0.2	69	73	29	18	2	2.4	0	1.2	132	0.1	13.2	31	1	121.5366	25.2968	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	中山區	12	中山	普通	67	細懸浮微粒	1.1	0.48	49	57	48	23	19	21	1.3	0.9	123	0.4	18.3	38	0	121.5265	25.0624	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	北投區	11	士林	普通	58	細懸浮微粒	1.4	0.4	42	55	33	18	16	16.5	0.1	0.3	20	0.3	15.1	33	0	121.5167	25.1033	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	北投區	64	陽明	良好	47	\N	1.3	0.28	52	51	40	12	6	6.1	0	\N	\N	0.2	10.5	28	1	121.5296	25.1827	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	大同區	16	大同	普通	72	細懸浮微粒	1.1	1.58	10	43	39	27	56	90	33.1	\N	\N	0.8	20	34	0	121.5134	25.0633	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	大安區	14	古亭	普通	67	臭氧八小時	1.5	0.37	46	60	34	21	13	14.4	0.5	0.6	119	0.3	16.1	34	1	121.5296	25.0206	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	松山區	15	松山	普通	65	細懸浮微粒	2.5	0.41	40	58	39	23	21	23.4	1.4	1.2	62	0.3	17.7	38	1	121.5786	25.05	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	萬華區	13	萬華	普通	65	細懸浮微粒	1.2	0.52	39	54	35	20	26	26.9	0.6	1.1	88	0.4	17.6	34	1	121.508	25.0465	2026/05/02 19:00:00	\N	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
\.

COPY public.environment_pressure_index (city, district, period, pressure_type, metric_name, station_count, avg_aqi, max_aqi, avg_pm2_5, avg_pm10, avg_o3_8hr, worst_status, dominant_pollutant, score, unit, source_dataset, updated_at) FROM stdin;
新北市	三重區	2026/05/02 19:00:00	空氣	AQI	2	66.5	68	18.1	37	48.5	普通	細懸浮微粒	68	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	土城區	2026/05/02 19:00:00	空氣	AQI	1	64	64	15.7	38	59	普通	臭氧八小時	64	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	新店區	2026/05/02 19:00:00	空氣	AQI	1	74	74	16.9	30	62	普通	臭氧八小時	74	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	新莊區	2026/05/02 19:00:00	空氣	AQI	1	70	70	18	48	55	普通	懸浮微粒	70	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	板橋區	2026/05/02 19:00:00	空氣	AQI	1	65	65	17.7	39	58	普通	細懸浮微粒	65	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	林口區	2026/05/02 19:00:00	空氣	AQI	1	64	64	17.4	32	57	普通	細懸浮微粒	64	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	樹林區	2026/05/02 19:00:00	空氣	AQI	1	68	68	18.6	29	59	普通	細懸浮微粒	68	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	永和區	2026/05/02 19:00:00	空氣	AQI	1	66	66	17.9	39	48	普通	細懸浮微粒	66	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	汐止區	2026/05/02 19:00:00	空氣	AQI	1	52	52	12.9	27	53	普通	細懸浮微粒	52	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	淡水區	2026/05/02 19:00:00	空氣	AQI	1	74	74	17.5	34	62	普通	臭氧八小時	74	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
新北市	石門區	2026/05/02 19:00:00	空氣	AQI	1	108	108	13.2	31	73	對敏感族群不健康	臭氧八小時	100	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	中山區	2026/05/02 19:00:00	空氣	AQI	1	67	67	18.3	38	57	普通	細懸浮微粒	67	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	北投區	2026/05/02 19:00:00	空氣	AQI	2	52.5	58	12.8	30.5	53	普通	細懸浮微粒	58	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	大同區	2026/05/02 19:00:00	空氣	AQI	1	72	72	20	34	43	普通	細懸浮微粒	72	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	大安區	2026/05/02 19:00:00	空氣	AQI	1	67	67	16.1	34	60	普通	臭氧八小時	67	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	松山區	2026/05/02 19:00:00	空氣	AQI	1	65	65	17.7	38	58	普通	細懸浮微粒	65	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
臺北市	萬華區	2026/05/02 19:00:00	空氣	AQI	1	65	65	17.6	34	54	普通	細懸浮微粒	65	score_0_100	MOENV AQX_P_432	2026-05-02T19:27:44+08:00
\.

CREATE INDEX IF NOT EXISTS environment_air_quality_stations_city_district_idx
ON public.environment_air_quality_stations (city, district);

CREATE INDEX IF NOT EXISTS environment_pressure_index_city_district_type_idx
ON public.environment_pressure_index (city, district, pressure_type);

SELECT pg_catalog.setval(
    'public.environment_air_quality_stations_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_air_quality_stations),
    true
);

SELECT pg_catalog.setval(
    'public.environment_pressure_index_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_pressure_index),
    true
);
