-- Air quality data seed
-- Generated by dataset-analysis/scripts/build_air_quality_assets.py

DROP TABLE IF EXISTS public.environment_air_quality_stations;
CREATE TABLE public.environment_air_quality_stations (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    site_id integer,
    site_name text,
    status text,
    aqi double precision,
    pollutant text,
    so2_ppb double precision,
    co_ppm double precision,
    o3_ppb double precision,
    o3_8hr_ppb double precision,
    pm10_ug_m3 double precision,
    pm2_5_ug_m3 double precision,
    no2_ppb double precision,
    nox_ppb double precision,
    no_ppb double precision,
    wind_speed_m_sec double precision,
    wind_direction_degree double precision,
    co_8hr_ppm double precision,
    pm2_5_avg_ug_m3 double precision,
    pm10_avg_ug_m3 double precision,
    so2_avg_ppb double precision,
    longitude double precision,
    latitude double precision,
    publish_time text,
    import_date text,
    source_dataset text,
    updated_at text
);

DROP TABLE IF EXISTS public.environment_pressure_index;
CREATE TABLE public.environment_pressure_index (
    id SERIAL PRIMARY KEY,
    city text,
    district text,
    period text,
    pressure_type text,
    metric_name text,
    station_count integer,
    avg_aqi double precision,
    max_aqi double precision,
    avg_pm2_5 double precision,
    avg_pm10 double precision,
    avg_o3_8hr double precision,
    worst_status text,
    dominant_pollutant text,
    score double precision,
    unit text,
    source_dataset text,
    updated_at text
);

COPY public.environment_air_quality_stations (city, district, site_id, site_name, status, aqi, pollutant, so2_ppb, co_ppm, o3_ppb, o3_8hr_ppb, pm10_ug_m3, pm2_5_ug_m3, no2_ppb, nox_ppb, no_ppb, wind_speed_m_sec, wind_direction_degree, co_8hr_ppm, pm2_5_avg_ug_m3, pm10_avg_ug_m3, so2_avg_ppb, longitude, latitude, publish_time, import_date, source_dataset, updated_at) FROM stdin;
新北市	三重區	67	三重	普通	63	細懸浮微粒	1.2	0.63	33	40	42	20	33	52.3	19	\N	\N	0.6	16.8	37	0	121.4938	25.0726	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	三重區	8	菜寮	普通	64	臭氧八小時	0.9	0.37	55	59	35	19	15	16.1	1	0.8	52	0.3	15.3	34	0	121.481	25.069	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	土城區	5	土城	普通	64	臭氧八小時	\N	\N	\N	59	48	19	\N	\N	\N	0.6	174	0.3	14.4	35	0	121.4519	24.9825	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	新店區	4	新店	普通	71	臭氧八小時	1.5	0.36	62	61	43	25	13	13.9	0.7	1.3	143	0.2	15.1	29	0	121.5378	24.9772	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	新莊區	7	新莊	普通	63	懸浮微粒	1.3	0.35	50	55	59	18	21	22.3	1.1	1.2	2	0.2	15.1	42	0	121.4325	25.038	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	板橋區	6	板橋	普通	59	細懸浮微粒	1.8	0.59	46	57	48	18	24	25.8	1.4	0.8	156	0.3	15.3	35	1	121.4587	25.013	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	林口區	9	林口	普通	61	臭氧八小時	1.8	0.26	57	58	32	13	9	10.9	1.2	0.7	257	0.2	14.3	28	1	121.3655	25.078	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	樹林區	311	新北（樹林）	普通	64	細懸浮微粒	1.4	0.34	59	59	32	22	9	11.2	1.4	0.6	94	0.3	17.1	28	1	121.3835	24.949	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	永和區	70	永和	普通	61	細懸浮微粒	1.8	0.65	47	46	47	22	22	25.9	2.9	0.6	109	0.6	16.2	40	1	121.5163	25.017	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	汐止區	2	汐止	良好	48	\N	1.8	0.49	53	52	29	14	10	11.4	1	1	34	0.2	12	23	1	121.6408	25.0662	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	淡水區	10	淡水	普通	67	臭氧八小時	1.3	0.26	59	60	42	19	13	14	0.9	\N	\N	0.2	17	30	0	121.4492	25.1645	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	石門區	84	富貴角	普通	93	臭氧八小時	0.7	0.18	74	68	36	13	1	1.2	0	0.6	15	0.1	11.6	32	1	121.5366	25.2968	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	中山區	12	中山	普通	68	細懸浮微粒	\N	\N	\N	55	38	17	\N	\N	\N	0.7	82	0.4	18.6	37	0	121.5265	25.0624	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	北投區	11	士林	普通	56	細懸浮微粒	1.5	0.32	44	55	35	17	15	15.8	0.4	0.2	29	0.2	14.4	34	0	121.5167	25.1033	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	北投區	64	陽明	良好	45	\N	1.2	0.25	49	49	33	12	4	4.5	0.1	\N	\N	0.2	11.2	25	0	121.5296	25.1827	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	大同區	16	大同	普通	62	細懸浮微粒	1.1	0.7	35	45	34	19	32	38.9	6.9	\N	\N	0.6	16.5	33	0	121.5134	25.0633	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	大安區	14	古亭	普通	64	臭氧八小時	1.9	0.41	51	59	42	20	19	21	1	0.9	111	0.3	14.2	32	1	121.5296	25.0206	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	松山區	15	松山	普通	61	臭氧八小時	2.7	0.37	50	58	40	21	16	18.3	1.5	1.1	41	0.3	15.5	37	1	121.5786	25.05	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	萬華區	13	萬華	普通	62	細懸浮微粒	1.2	0.44	47	55	39	19	21	21.8	0.8	0.4	357	0.4	16.4	33	0	121.508	25.0465	2026/05/02 17:00:00	\N	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
\.

COPY public.environment_pressure_index (city, district, period, pressure_type, metric_name, station_count, avg_aqi, max_aqi, avg_pm2_5, avg_pm10, avg_o3_8hr, worst_status, dominant_pollutant, score, unit, source_dataset, updated_at) FROM stdin;
新北市	三重區	2026/05/02 17:00:00	空氣	AQI	2	63.5	64	16.05	35.5	49.5	普通	細懸浮微粒	64	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	土城區	2026/05/02 17:00:00	空氣	AQI	1	64	64	14.4	35	59	普通	臭氧八小時	64	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	新店區	2026/05/02 17:00:00	空氣	AQI	1	71	71	15.1	29	61	普通	臭氧八小時	71	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	新莊區	2026/05/02 17:00:00	空氣	AQI	1	63	63	15.1	42	55	普通	懸浮微粒	63	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	板橋區	2026/05/02 17:00:00	空氣	AQI	1	59	59	15.3	35	57	普通	細懸浮微粒	59	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	林口區	2026/05/02 17:00:00	空氣	AQI	1	61	61	14.3	28	58	普通	臭氧八小時	61	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	樹林區	2026/05/02 17:00:00	空氣	AQI	1	64	64	17.1	28	59	普通	細懸浮微粒	64	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	永和區	2026/05/02 17:00:00	空氣	AQI	1	61	61	16.2	40	46	普通	細懸浮微粒	61	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	汐止區	2026/05/02 17:00:00	空氣	AQI	1	48	48	12	23	52	良好	\N	48	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	淡水區	2026/05/02 17:00:00	空氣	AQI	1	67	67	17	30	60	普通	臭氧八小時	67	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
新北市	石門區	2026/05/02 17:00:00	空氣	AQI	1	93	93	11.6	32	68	普通	臭氧八小時	93	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	中山區	2026/05/02 17:00:00	空氣	AQI	1	68	68	18.6	37	55	普通	細懸浮微粒	68	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	北投區	2026/05/02 17:00:00	空氣	AQI	2	50.5	56	12.8	29.5	52	普通	細懸浮微粒	56	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	大同區	2026/05/02 17:00:00	空氣	AQI	1	62	62	16.5	33	45	普通	細懸浮微粒	62	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	大安區	2026/05/02 17:00:00	空氣	AQI	1	64	64	14.2	32	59	普通	臭氧八小時	64	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	松山區	2026/05/02 17:00:00	空氣	AQI	1	61	61	15.5	37	58	普通	臭氧八小時	61	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
臺北市	萬華區	2026/05/02 17:00:00	空氣	AQI	1	62	62	16.4	33	55	普通	細懸浮微粒	62	score_0_100	MOENV AQX_P_432	2026-05-02T17:24:55+08:00
\.

CREATE INDEX IF NOT EXISTS environment_air_quality_stations_city_district_idx
ON public.environment_air_quality_stations (city, district);

CREATE INDEX IF NOT EXISTS environment_pressure_index_city_district_type_idx
ON public.environment_pressure_index (city, district, pressure_type);

SELECT pg_catalog.setval(
    'public.environment_air_quality_stations_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_air_quality_stations),
    true
);

SELECT pg_catalog.setval(
    'public.environment_pressure_index_id_seq',
    (SELECT COALESCE(MAX(id), 0) FROM public.environment_pressure_index),
    true
);
