--
-- EV Charge source data
-- Values are grams per person per day.
--

DROP TABLE IF EXISTS public.taipei_ev_charging;

CREATE TABLE public.taipei_ev_charging (
    city text,
    station_name text
);

COPY public.taipei_ev_charging (
city,
station_name
) FROM stdin;
Taipei	國立臺灣大學新南地下停車場
Taipei	陽明山第二停車場
Taipei	慶昌橋下停車場
Taipei	福林公園地下停車場
Taipei	大安森林公園地下停車場
Taipei	光復北路平面停車場
Taipei	玉成國小地下停車場
Taipei	松德大樓地下停車場
Taipei	金華公園地下停車場
Taipei	五常街臨時平面停車場
Taipei	國立臺灣大學水源校區平面停車場
Taipei	陽明山立體停車場
Taipei	南湖高中運動中心停車場
Taipei	立農公園地下停車場
Taipei	前港公園地下停車場
Taipei	瑠公國中停車場
Taipei	水源停車場
Taipei	中油大樓停車場
Taipei	臺北市災害應變中心地下停車場
Taipei	北投國中教職員工停車場
Taipei	府前廣場地下停車場
Taipei	長春路平面停車場
Taipei	松山高中地下停車場
Taipei	國立臺灣大學生醫工程館地下停車場
Taipei	大豐公園地下停車場
Taipei	雙園國中地下停車場
Taipei	辛亥水安停車場
Taipei	USPACE 福林第二停車場
Taipei	福星社會住宅地下停車場
Taipei	進安公園地下停車場
Taipei	松壽廣場地下停車場
Taipei	信義路5段150巷臨時平面停車場
Taipei	大龍峒社會住宅地下停車場
Taipei	台灣聯通萬華安居A停車場
Taipei	台灣聯通萬華安居B停車場
Taipei	舊宗社會住宅地下停車場
Taipei	水源快速道路高架橋下
Taipei	忠信廣場地下停車場
Taipei	康寧平面停車場
Taipei	環山平面停車場
Taipei	臺北市芳和實驗中學
Taipei	國立臺灣大學芳蘭第一平面停車場
Taipei	關渡水岸自然公園平面停車場
Taipei	東湖國小地下停車場
Taipei	青年公園高爾夫球場地下停車場
Taipei	公館停車場
Taipei	臺北市立成功高級中學綜合大樓地下停車場
Taipei	洲子站
Taipei	景文平面停車場
Taipei	松德臨時平面停車場
Taipei	興隆公園地下停車場
Taipei	百齡高中地下停車場
Taipei	開勝平面停車場
Taipei	洲子立體停車場
Taipei	古亭國中地下停車場
Taipei	龍門國中地下停車場
Taipei	正氣橋下平面停車場
Taipei	龍江平面停車場
Taipei	政大三街臨時平面停車場
Taipei	洲美運動公園地下停車場
Taipei	萬華車站地下停車場
Taipei	至誠平面停車場
Taipei	興中立體停車場
Taipei	萬華國中地下停車場
Taipei	台北市公有士林市場停車場
Taipei	環南停車場
Taipei	民有市場地下停車場
Taipei	文湖平面停車場
Taipei	社子國小地下停車場
Taipei	樟新平面停車場
Taipei	信義廣場地下停車場
Taipei	石潭平面停車場
Taipei	永盛公園地下停車場
Taipei	臺大癌醫中心分院地下停車場
Taipei	關渡醫院旁平面停車場
Taipei	蘭雅公園地下停車場
Taipei	大龍國小地下停車場
Taipei	南港高中停車場
Taipei	新和國小地下停車場
Taipei	國立臺灣大學校總區平面停車場
Taipei	臺北市內湖區潭美國民小學地下停車場
Taipei	福山平面停車場
Taipei	耕莘文教院前平面停車場
Taipei	民生立體停車場
Taipei	臺北市大同運動中心地下平面停車場
Taipei	信義國小地下停車場
Taipei	康樂合署大樓地下停車場
Taipei	福港街平面停車場
Taipei	中山運動中心旁臨時平面停車場
Taipei	世貿公園地下停車場
Taipei	海光公園地下停車場
Taipei	蓬萊國小地下停車場
Taipei	國立臺灣大學辛亥地下停車場
Taipei	臺北市松山家商附設夜間及假日停車場
Taipei	松山工農地下停車場
Taipei	新生公園停車場
Taipei	三福街平面停車場
Taipei	景豐臨時平面停車場
Taipei	大稻埕公園地下停車場
Taipei	福國路橋下平面停車場
Taipei	便利停車場大安地政事務所一站
Taipei	南港國小地下停車場
Taipei	啟聰學校地下停車場
Taipei	偶戲博物館地下停車場
Taipei	豐年運動公園平面停車場
Taipei	大湖活動中心暨溫水游泳池停車場
Taipei	興雅國中地下停車場
Taipei	松山國小地下停車場
Taipei	大安高工地下停車場
Taipei	保儀路平面停車場
Taipei	吉祥平面停車場
Taipei	臺北市建成綜合大樓停車場
Taipei	陽明山花鐘停車場
Taipei	兒童育樂中心平面停車場
Taipei	成淵高中地下停車場
Taipei	辛亥國小地下停車場
Taipei	艋舺公園地下停車場
Taipei	中山國中地下停車場
Taipei	臺北市大同區太平國民小學停車場
Taipei	長安國小地下停車場
Taipei	萬興國小地下停車場
Taipei	西松高中地下停車場
Taipei	松山車站地下停車場
Taipei	延平國小地下停車場
Taipei	臺北大橋橋下停車場
Taipei	玉成公園地下停車場
Taipei	春光公園地下停車場
Taipei	三張里地下停車場
Taipei	市民大道建復段停車場
Taipei	林森公園地下停車場
Taipei	Times浩瀚運創西門館
Taipei	萬芳八號公園停車場
Taipei	嘉興公園地下停車場
Taipei	金湖臨時平面停車場
Taipei	長春路龍江路臨時平面停車場
Taipei	五分埔公園地下停車場
Taipei	石牌國小地下停車場
Taipei	文昌國小地下停車場
Taipei	榮星花園地下停車場
Taipei	景勤二號公園地下停車場
Taipei	莒光社會住宅地下停車場
Taipei	臺北市萬華區行政中心地下停車場
Taipei	花博公園圓山地下停車場
Taipei	USPACE三寶大樓地下停車場
Taipei	好市多北投分公司
Taipei	USPACE北投晶泉丰旅停車場
Taipei	大安國中地下停車場
Taipei	USPACE 福林第一停車場
Taipei	臺北市內湖區內湖國民小學孝悌樓地下停車場
Taipei	青年一期社會住宅地下停車場
Taipei	峨眉立體停車場
Taipei	臺北市大龍新城地下停車場
Taipei	好市多內湖店停車場
Taipei	便利停車場瑞光站
Taipei	南港軟體園區南軟大樓地下室停車場
Taipei	南港軟體園區經貿大樓地下停車場
Taipei	大港墘公園地下停車場
Taipei	東湖立體停車場
Taipei	USPACE晶華酒店附設停車場
Taipei	大潤發中崙店停車場
Taipei	便利停車場民生站
Taipei	永田停車場
Taipei	市民大道復敦段停車場
Taipei	市民大道敦延段停車場
Taipei	市民大道延吉段停車場
Taipei	健康1區社會住宅地下停車場
Taipei	健康2區社會住宅地下停車場
Taipei	王朝大酒店
Taipei	宏國大樓停車場
Taipei	USPACE富邦敦北大樓
Taipei	臺北文創停車場
Taipei	台北君悅酒店停車場
Taipei	USPACE 宏泰A19購物中心停車場
Taipei	USPACE交易一號停車場
Taipei	USPACE交易二號停車場
Taipei	大安運動中心停車場
Taipei	三井飯店停車場
Taipei	富邦金融大樓停車場
Taipei	USPACE仁愛帝寶停車場
Taipei	臺北市立金華國民中學
Taipei	USPACE電信大樓停車場
Taipei	富山杭州南路停車場
Taipei	便利停車場大安地政事務所站
Taipei	臺北和平籃球館停車場
Taipei	便利停車場富敦站
Taipei	振華公園地下停車場
Taipei	168停車聯盟-士林場
Taipei	168停車聯盟-大龍場
Taipei	168停車聯盟-西園國宅場
Taipei	168停車聯盟-昆陽場(南港信義保管場)
Taipei	168停車聯盟-水源市場
Taipei	168停車聯盟-華視停車場
Taipei	168停車聯盟-興岩社福大樓
Taipei	景美女中地下停車場
Taipei	永建國小地下停車場
Taipei	興隆D1社會住宅地下停車場
Taipei	興隆D2社會住宅地下停車場
Taipei	臺北市內湖區新湖國民小學活動中心地下停車場
Taipei	民權公園地下停車場
Taipei	臺北市立明倫高級中學停車場
Taipei	濱江國中地下停車場
Taipei	華榮社宅場
Taipei	臺北市中正區社會福利綜合大樓附設停車場
Taipei	敦北翠苑停車場
Taipei	助安企業有限公司懷愛館地下停車場
Taipei	東明乙區社會住宅地下停車場
Taipei	兒童新樂園停車場
Taipei	北投稻香地下停車場
Taipei	臺北田徑場平面、地下停車場
Taipei	臺北市立大學天母校區體育館平面停車場
Taipei	國立臺灣大學公館平面停車場
Taipei	臺北市立大學天母校區教學、行政科資大樓地下停車場
Taipei	東明甲區社會住宅地下停車場
Taipei	臺北體育館地下停車場
Taipei	健康國小地下停車場
Taipei	附中公園地下停車場
Taipei	嘟嘟房捷運石牌站停車場
Taipei	嘟嘟房捷運唭哩岸站停車場
Taipei	嘟嘟房捷運北投站停車場
Taipei	嘟嘟房捷運新北投站停車場
Taipei	嘟嘟房捷運忠義站停車場
Taipei	嘟嘟房捷運內湖機廠站停車場
Taipei	嘟嘟房捷運芝山站停車場
Taipei	嘟嘟房捷運士林站停車場
Taipei	建國北路高架橋下O區
Taipei	建國北路高架橋下IB區
Taipei	建國北路高架橋下J區
Taipei	建國北路高架橋下G區
Taipei	建國北路高架橋下H區
Taipei	建國北路高架橋下E區
Taipei	建國北路高架橋下F區
Taipei	建國北路高架橋下B區
Taipei	建國北路高架橋下C區
Taipei	建國北路高架橋下D區
Taipei	建國北路高架橋下A區
Taipei	僑安地下停車場
Taipei	市民大道中林段停車場
Taipei	市民大道林金段停車場
Taipei	八德立體停車場
Taipei	中山堂地下停車場
Taipei	中崙高中地下停車場
Taipei	建國北路高架橋下IA區
Taipei	七星公園地下停車場
Taipei	陽明大學停車場
Taipei	臺北市立明德國民中學附設停車場
Taipei	巧愛公寓地下室停車場
Taipei	新北投公園停車場
Taipei	北投運動中心停車場
Taipei	博客停車場-家福公館場
Taipei	潭美停車場
Taipei	南港重陽停車場
Taipei	臺北市立聯合醫院-陽明院區停車場
Taipei	臺北市立聯合醫院-中興院區停車場
Taipei	朝陽公園地下停車場
Taipei	叭叭房亞太C區停車場
Taipei	CITYLINK 內湖店停車場
Taipei	臺北市南港運動中心停車場
Taipei	台北花卉產銷股份有限公司A館
Taipei	台北花卉產銷股份有限公司B館
Taipei	建成公園地下停車場
Taipei	建成國中地下停車場
Taipei	臺北市立大同高級中學附設停車場
Taipei	臺北農產運銷股份有限公司第二果菜批發市場地下三樓停車場(濱江市場地下停車場)
Taipei	台北美福大飯店停車場
Taipei	台北地下街停車場
Taipei	臺北市立聯合醫院-婦幼院區停車場
Taipei	臺北市立聯合醫院-和平院區停車場
Taipei	臺北市中正運動中心地下停車場
Taipei	民生社區中心地下停車場
Taipei	市府轉運站停車場
Taipei	臺北市立聯合醫院-松德院區停車場
Taipei	詮營信義101停車場
Taipei	科技服務大樓附設停車場
Taipei	臺北市立聯合醫院-仁愛院區停車場
Taipei	景美國小地下停車場
Taipei	青年公園棒球場地下停車場
Taipei	歐特儀股份有限公司捷運木柵站轉乘停車場
Taipei	遠企中心地下停車場
Taipei	臺北市公有士東市場地下室停車場
Taipei	臺北市文山運動中心停車場
Taipei	葫蘆國小夜間停車場
Taipei	Times 松山運動中心
Taipei	公館路平面停車場
Taipei	公舘路228巷平面停車場
Taipei	承德公園地下停車場
Taipei	太平洋崇光百貨股份有限公司天母店停車場
Taipei	東和公園平面停車場
Taipei	忠誠路（二）平面停車場
Taipei	士林高商停車場
Taipei	和興水岸社會住宅地下停車場
Taipei	青年二期社會住宅地下停車場
Taipei	廣慈3區社會住宅地下停車場
Taipei	興隆A區社會住宅地下停車場
Taipei	延平北路5段1巷平面停車場
Taipei	社正路平面停車場
Taipei	福林路平面停車場
Taipei	懷德街55巷平面停車場
Taipei	大業路280巷臨時平面停車場
Taipei	市民大道塔城段停車場
Taipei	華江橋下與雙層小型車停車場
Taipei	新和庭園平面停車場
Taipei	安康公車調度站臨時平面停車場
Taipei	叭叭房陽光大樓停車場
Taipei	南港車站地下停車場
Taipei	市民大道公中段停車場
Taipei	中山北路3段55巷平面停車場
Taipei	臺北農產運銷股份有限公司第二果菜批發市場停車場
Taipei	城中社會福利綜合大樓地下停車場
Taipei	臺北市客家文化中心附設地下停車場
Taipei	遠東百貨信義分公司
Taipei	吳興街284巷臨時平面停車場
Taipei	太平洋崇光百貨股份有限公司復興店停車場
Taipei	辛亥高架橋下停車場
Taipei	太平洋崇光百貨股份有限公司忠孝店停車場
Taipei	國立臺灣師範大學和平校區Ⅰ運動場地下停車場
Taipei	六張犁1區社宅停車場
Taipei	國立臺灣師範大學和平校區Ⅱ羅馬廣場地下停車場
Taipei	和平東路四段381巷平面停車場
Taipei	興隆市場旁平面停車場
Taipei	國立臺灣師範大學附屬高級中學體育教學館地下停車場
Taipei	六張犁2區社宅停車場
Taipei	南港停車場
Taipei	經貿社會住宅地下停車場
Taipei	臺北市士林區行政中心地下停車場
Taipei	振興公園地下停車場
Taipei	臺北市萬華區老松國民小學附設停車場
Taipei	臺北市大同區行政中心地下停車場
Taipei	臺北市網球中心停車場
Taipei	臺北市內湖區麗山國民小學停車場
Taipei	南湖國小活動中心附設停車場
Taipei	臺北市南港區胡適國小地下停車場
Taipei	臺北市南港區東新國民小學停車場
Taipei	內湖區行政中心停車場
Taipei	中山區行政中心停車場
Taipei	中山大樓停車場
Taipei	便利停車場萬國站
Taipei	廣慈1區社會住宅地下停車場
Taipei	廣慈2區社會住宅地下停車場
Taipei	萬芳醫院附設停車場
Taipei	驛林交通股份有限公司興隆站
Taipei	科技大樓地下停車場
Taipei	成德國中運動中心停車場
Taipei	關渡自然公園停車場
Taipei	內湖垃圾焚化廠停車場
Taipei	力行停車場
Taipei	台灣聯通延吉好室停車場
Taipei	臺北市立天文科學教育館地下及戶外平面停車場
Taipei	環南市場停車場
Taipei	華江高中活動中心地下停車場
Taipei	台北車站K區地下街停車場
Taipei	水岸停車場
Taipei	臺北車站西區地下停車場
Taipei	臺北車站東區地下停車場
Taipei	北寧路地下停車場
Taipei	臺北大巨蛋園區停車場
Taipei	助安企業股份有限公司黎元停車場
Taipei	助安企業股份有限公司辛亥路高架橋下停車場
Taipei	168停車聯盟-中華信義場
Taipei	臺北市文山區行政中心停車場
Taipei	嘟嘟房捷運木柵機廠站停車場
Taipei	木柵社會住宅地下停車場
Taipei	嘟嘟房動物園站停車場
Taipei	永平社會住宅地下停車場
Taipei	168停車聯盟-大安場
Taipei	中山國中站
Taipei	林森公園站
Taipei	玉成國小站
Taipei	松壽廣場站
Taipei	捷運芝山站
Taipei	捷運忠義站
Taipei	捷運唭哩岸站
Taipei	捷運石牌站
Taipei	捷運北投站
Taipei	捷運新北投站
Taipei	建國高架站A區
Taipei	建國高架站C區
Taipei	建國高架站D區
Taipei	建國高架站E區
Taipei	建國高架站G區
Taipei	建國高架站H區
Taipei	建國高架站IB區
Taipei	建國高架站J區
Taipei	建國高架站O區
Taipei	市民大道-中林站
Taipei	市民大道-林金站
Taipei	捷運士林站
Taipei	七星公園站
Taipei	八德立體站
Taipei	捷運內湖機廠站
Taipei	附中公園站
Taipei	建國高架站
Taipei	建國高架站B區
Taipei	府前廣場站
Taipei	建國高架站F區
Taipei	中崙高中站
Taipei	偶戲博物館站
Taipei	中山堂站
Taipei	僑安站
Taipei	健康國小站
Taipei	台北小巨蛋站
Taipei	市民大道-公中站
Taipei	市民大道-塔城站
Taipei	承德公園站
NewTaipei	THPS
NewTaipei	新北－土城日月光廣場(B3)
NewTaipei	新埔國小地下停車場
NewTaipei	頭前平面停車場充電站
NewTaipei	宏匯思源公共停車場
NewTaipei	麗林國小停車場
NewTaipei	林口展悅CEO豪辦站
NewTaipei	DARA-聯通雙和慈濟站
NewTaipei	DARA-宏匯廣場站
NewTaipei	汐止區公所
NewTaipei	板橋中山停車場
NewTaipei	忠厚地下停車場
NewTaipei	俥亭停車事業瑞芳八斗子營業所
NewTaipei	雙和醫院停車場
NewTaipei	雙和醫院二停車場
NewTaipei	板橋大遠百
NewTaipei	亞東科技大學地下停車場
NewTaipei	土城國民運動中心
NewTaipei	三重國民運動中心
NewTaipei	捷運蘆洲站
NewTaipei	捷運紅樹林站
NewTaipei	捷運淡水站
NewTaipei	蘆洲功學社站
NewTaipei	新北－汐止日月光家飾館
NewTaipei	新北－中和環球購物中心
NewTaipei	新北－新店
NewTaipei	新北－土城日月光廣場
NewTaipei	新北－三重愛買
NewTaipei	新北－滬尾藝文休閒園區
NewTaipei	新北－新莊
NewTaipei	新北 - 中和環球購物中心
NewTaipei	林口A9環球購物中心
NewTaipei	新北 - 黃金海岸高爾夫球場
NewTaipei	璞石麗緻溫泉會館
NewTaipei	新北－三重愛買
NewTaipei	新北－三峽
NewTaipei	168parking 蘆洲三民停車場
NewTaipei	新北－林口亞昕福朋喜來登酒店
NewTaipei	新北 - 八里福朋喜來登酒店
NewTaipei	美麗人生產後護理之家
NewTaipei	充電飽_新北產業園區服務中心站
NewTaipei	好市多汐止店B1充電站
NewTaipei	好市多中和店B1充電站
NewTaipei	新北市板橋國民運動中心B1充電站
NewTaipei	好市多新莊店4F充電站
NewTaipei	24TPS 永固便利停（南山威力站）
NewTaipei	大潤發中和店
NewTaipei	新莊典華B2充電站
NewTaipei	新北市三重區三光國民小學
NewTaipei	新北永和比漾廣場
NewTaipei	MITSUI OUTLET PARK 林口Ⅰ館
NewTaipei	新北市林口國民運動中心
NewTaipei	新北市青少年圖書館
NewTaipei	宏匯思源i-Tower大樓
NewTaipei	新北三峽公有市場
NewTaipei	新北民享公有市場
NewTaipei	新北泰山公有市場
NewTaipei	新北捷運幸福站立體停車場
NewTaipei	MITSUI OUTLET PARK 林口Ⅱ館
NewTaipei	新北永福國小地下停車場
NewTaipei	新北龍門公園地下停車場
NewTaipei	新北二重國中地下停車場
NewTaipei	新北厚德國小地下停車場
NewTaipei	新北五常地下停車場
NewTaipei	新北聯邦公園地下停車場
NewTaipei	新北正義公園地下停車場
NewTaipei	新北溪美立體停車場
NewTaipei	新北八里區第一立體停車場
NewTaipei	新北五股區工商路立體停車場
NewTaipei	新北智興立體停車場
NewTaipei	新北楓樹腳公園地下停車場
NewTaipei	新北義學立體停車場
NewTaipei	新北澳底公園地下停車場
NewTaipei	新北三峽國小地下停車場
NewTaipei	新北金城立體停車場
NewTaipei	新北三張公園地下停車場
NewTaipei	新北光興國小地下停車場
NewTaipei	新北碧華國小地下停車場
NewTaipei	新北光榮國小地下停車場
NewTaipei	新北興穀國小地下停車場
NewTaipei	新北市三民立體停車場
NewTaipei	新北市水碓立體停車場
NewTaipei	新北市民生立體停車場
NewTaipei	新北長壽公園地下停車場
NewTaipei	新北延吉立體停車場
NewTaipei	新北三民地下停車場
NewTaipei	新北裕生立體停車場
NewTaipei	新北學成公園地下停車場
NewTaipei	新北員和公園地下停車場
NewTaipei	新北綠湖公園地下停車場
NewTaipei	新北市瑞芳區立體停車場
NewTaipei	新北市蘆洲國小地下停車場
NewTaipei	新北市鷺江立體停車場
NewTaipei	新北市成功地下停車場
NewTaipei	新北市溪墘地下停車場
NewTaipei	新北市仁愛立體停車場
NewTaipei	新北三重商工地下停車場
NewTaipei	新北市中正停車場
NewTaipei	新北市後港公園地下停車場
NewTaipei	新北市頭前國中地下停車場
NewTaipei	新北市民安國民小學地下停車場
NewTaipei	新北正義國小地下停車場
NewTaipei	新北江翠國小地下停車場
NewTaipei	新北特專三臨時平面停車場
NewTaipei	新北新埔國小地下停車場
NewTaipei	新北錦和運動公園地下停車場
NewTaipei	新北華翠橋下平面停車場
NewTaipei	新北臺北紙廠停車場
NewTaipei	新北華東平面停車場
NewTaipei	新北江翠102平面停車場
NewTaipei	新北台65高架橋下停車場
NewTaipei	新北中洲平面停車場
NewTaipei	新北永豐平面停車場
NewTaipei	新北明德平面停車場
NewTaipei	新北圓通平面停車場
NewTaipei	新北安和公園臨時平面停車場
NewTaipei	新北三鶯轉運站平面停車場
NewTaipei	新北江翠國中游泳池共構地下停車場
NewTaipei	新北四維公園地下停車場
NewTaipei	新北音樂公園地下停車場
NewTaipei	新北市立鷺江國民中學地下停車場
NewTaipei	新北市新莊國中運動場地下停車場
NewTaipei	新北市中山停車場
NewTaipei	新北二重公園地下停車場
NewTaipei	新北中興低碳立體停車場
NewTaipei	新北兒童遊戲場地下停車場
NewTaipei	新北新店高中地下停車場
NewTaipei	新北板橋國小地下停車場
NewTaipei	新北重慶公園地下停車場
NewTaipei	新北市民廣場地下停車場
NewTaipei	新北板橋國民中學地下停車場
NewTaipei	新北民生公園地下停車場
NewTaipei	新北民權立體停車場
NewTaipei	新北府後立體停車場
NewTaipei	新北市立圖書館地下停車場
NewTaipei	新北板橋高中地下停車場
NewTaipei	新北中山國小地下停車場
NewTaipei	新北忠孝國民中學地下停車場
NewTaipei	新北五權公園地下停車場
NewTaipei	新北水柳腳立體停車場
NewTaipei	新北中和國小地下停車場
NewTaipei	新北民樂立體停車場
NewTaipei	新北中和地政事務所及稅捐稽徵處
NewTaipei	新北中山立體停車場
NewTaipei	新北停三立體停車場
NewTaipei	新北林口公車轉運站平面停車場
NewTaipei	新北中央公園地下停車場
NewTaipei	新北市永康公園地下停車場
NewTaipei	新北市金山立體停車場
NewTaipei	新北市新莊運動公園地下停車場
NewTaipei	新北仁愛公園地下停車場
NewTaipei	新北永和國小地下停車場
NewTaipei	新北秀朗國民小學地下停車場
NewTaipei	新北福和國中地下停車場
NewTaipei	新北網溪國小地下停車場
NewTaipei	新北大豐地下停車場
NewTaipei	新北安康立體停車場
NewTaipei	新北北新地下停車場
NewTaipei	新北寶橋立體停車場
NewTaipei	新北第七立體停車場
NewTaipei	新北樹林藝文綜合行政大樓地下停車場
NewTaipei	新北景新立體停車場
NewTaipei	新北烏來立體停車場
NewTaipei	新北萬板高架橋下停車場
NewTaipei	新北民德立體停車場
NewTaipei	新北民享公園地下停車場
NewTaipei	新北秀山公園地下停車場
NewTaipei	新北佳和公園地下停車場
NewTaipei	新北高工地下停車場
NewTaipei	新北重陽公園地下停車場
NewTaipei	新北頂溪國小地下停車場
NewTaipei	新北中港平面停車場
NewTaipei	新北公八公園平面停車場
NewTaipei	歐特儀_三峽台北大學運動場停車場
NewTaipei	力揚_板橋體育場
NewTaipei	新北建昇淡水行政中心
NewTaipei	新北國家電影及視聽文化中心
NewTaipei	新北晶冠廣場
NewTaipei	歐特儀_新北文中小平面停車場
NewTaipei	新北興穀國小操場地下停車場
NewTaipei	易亭_新北新店中正停車場
NewTaipei	新北市新莊國民運動中心
NewTaipei	新北新莊農會_信用部
NewTaipei	力揚_新北蘆洲重陽大樓停車場
NewTaipei	力揚_新北中和安邦青年社會住宅
NewTaipei	新北市八里區行政中心
NewTaipei	力揚_新北金山老街文化一路停車場
NewTaipei	白雲國民小學
NewTaipei	興南國民小學
NewTaipei	星舟x城市車旅_汐止遠雄iFG
NewTaipei	星舟x城市車旅_三重冠德心天匯
NewTaipei	學府停車場
NewTaipei	立言停車場
NewTaipei	淞和快充 土城站 evbar
NewTaipei	全尚大同路充電站 evbar
NewTaipei	全尚國際二街充電站 evbar
NewTaipei	新莊思源快充站 evbar
NewTaipei	全尚學成路充電站 evbar
NewTaipei	全尚粗坑里辦事處充電站 evbar
NewTaipei	中和充電站 evbar
NewTaipei	全尚誠陽車業 evbar
NewTaipei	全方位停車場鶯桃站 evbar
NewTaipei	新北市立江翠國民中學 evbar
NewTaipei	汐科站停車場 evbar
NewTaipei	蘆洲區忠義國小地下停車場 evbar
NewTaipei	Acon-eco新北新店央北站
NewTaipei	Acon-eco新北新莊昌平站
NewTaipei	Acon-eco新北蘆洲仁愛街站
NewTaipei	Acon-eco新北新店央北青年社宅站
NewTaipei	Acon-eco新北土城員和青年社宅站
NewTaipei	Acon-eco新北淡水國小站
NewTaipei	Acon-eco新北新莊副都84站
NewTaipei	Acon-eco新北永和運動中心站
NewTaipei	Acon-eco新北台北港站
NewTaipei	Acon-eco新北林口忠孝站
NewTaipei	Acon-eco新北碧潭東岸停車場站
NewTaipei	Acon-eco新北碧潭西岸停車場站
NewTaipei	Acon-eco新北碧潭渡船頭停車場站
NewTaipei	Acon-eco新北汐止同興停車場站
NewTaipei	Acon-eco新北樹林區公所站
NewTaipei	Acon-eco新北林口檔案館站
NewTaipei	Acon-eco新北三芝淺水灣站
NewTaipei	Acon-eco新北金山中角灣站
NewTaipei	Acon-eco新北新店民權中正站
NewTaipei	Acon-eco新北全聯林口文化北站
NewTaipei	全聯林口公園站
NewTaipei	全聯三重仁義站
NewTaipei	YES八里永續環境教育中心
NewTaipei	新北市淡水區公所
NewTaipei	新北市土城區公所
NewTaipei	新北－林口亞昕福朋喜來登酒店
NewTaipei	板橋遠百中山店
NewTaipei	雲樁科技鄧公國小站
NewTaipei	五股運動中心
NewTaipei	蘆洲運動中心
NewTaipei	林口亞昕福朋喜來登酒店
NewTaipei	國立臺北大學
NewTaipei	捷運江子翠站
NewTaipei	林口世大運選手村社會住宅地下停車場A區
NewTaipei	林口世大運選手村社會住宅地下停車場B區
NewTaipei	林口世大運選手村社會住宅地下停車場C區
NewTaipei	林口世大運選手村社會住宅地下停車場D區
NewTaipei	新莊體育園區停車場
NewTaipei	捷運迴龍站轉乘停車場
NewTaipei	板橋車站地下停車場
NewTaipei	捷運海山站轉乘停車場
NewTaipei	捷運永寧站轉乘停車場
NewTaipei	捷運頂埔站轉乘停車場
NewTaipei	上嘉管理顧問有限公司汐科營業所
NewTaipei	城市車旅三重元信(三重元信2)
NewTaipei	ECAR-台灣藝術大學站
NewTaipei	及泰企業有限公司紅毛城停車場
NewTaipei	根基國際有限公司青潭國民小學停車場
NewTaipei	國雲停車-府中汽車停車場
NewTaipei	江翠停五平面停車場
NewTaipei	市立殯儀館停車場
NewTaipei	新北市立殯儀館三峽火化立體停車場
\.
